backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/blog"
public_folder: "/assets/blog/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "/src/pages/blog/blog_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Slug (page name on the Url)", name: "slug", widget: "string", default: "", required: true}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "date-time", required: true}
      - {label: "Featured Image", name: "imagePrimary", widget: "image" , required: true}
      - {label: "Image Caption", name: "imageAlt", widget: "string" , required: true}
      - {label: "Is This A Featured Post", name: "isFeatured", widget: "boolean", default: false, required: true}
      - {label: "Description", name: "description", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
